-- we HAVE TO FIND THE SINIOR MOST EMPLOYEE FROM DATABASE
SELECT FIRST_NAME,LAST_NAME FROM employee
ORDER BY LEVELS DESC 
LIMIT 1;

-- 2 WHICH COUNTRY HAVE THE MOST INVOICES(MOST BILL MADE WILL BE KNOWN BY BELLOW QUERRY)

SELECT  COUNT(*) AS C,
BILLING_COUNTRY FROM INVOICE
GROUP BY BILLING_COUNTRY 
ORDER BY C DESC
LIMIT 1;

-- 3 WHAT IS TOP 3 VALUES OF TOTAL INVOICES

SELECT TOTAL FROM INVOICE
ORDER BY TOTAL DESC
LIMIT 3;

--4
SELECT BILLING_CITY,
SUM(TOTAL) AS NEW_TOTAL 
FROM INVOICE
GROUP BY BILLING_CITY
ORDER BY NEW_TOTAL DESC
LIMIT 1;

--5
SELECT C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
SUM(I.TOTAL) AS TOTAL_SPEND
FROM CUSTOMER C
JOIN INVOICE I
ON C.CUSTOMER_ID = I.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID 
ORDER BY TOTAL_SPEND DESC
LIMIT 1;

-- QUESTION SET 2 1)
-- WE HAVE TO JOIN THE CUSTOMER TABLE WITH GENRE
SELECT C.EMAIL,
C.FIRST_NAME,
C.LAST_NAME 
FROM CUSTOMER C JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON I.INVOICE_ID=IL.INVOICE_ID
WHERE TRACK_ID IN(
	SELECT TRACK_ID FROM TRACK T
	JOIN GENRE G ON T.GENRE_ID= G.GENRE_ID
	WHERE G.NAME LIKE 'Rock'
)
ORDER BY C.EMAIL;

-- 2) 
select AR.ARTIST_ID,AR.NAME,
COUNT(AR.ARTIST_ID) AS NUMBER_OF_SONGS
from track T 
JOIN ALBUM A ON T.ALBUM_ID = A.ALBUM_ID 
JOIN GENRE G ON T.GENRE_ID= G.GENRE_ID
JOIN ARTIST AR ON AR.ARTIST_ID= A.ARTIST_ID
WHERE G.NAME LIKE 'Rock'
GROUP BY AR.ARTIST_ID
ORDER BY NUMBER_OF_SONGS DESC
LIMIT 10;

--3)

SELECT name,TRACK_ID,
MILLISECONDS
FROM TRACK
WHERE MILLISECONDS > (
	SELECT AVG(MILLISECONDS) 
	FROM TRACK)
ORDER BY MILLISECONDS DESC;


--3 1)
WITH BEST_SELLING_ARTIST AS (
	SELECT AR.ARTIST_ID AS ARTIST_ID,
	AR.NAME AS ARTIST_NAME,
	SUM(IL.UNIT_PRICE*IL.QUANTITY) AS TOTAL_SALE
	FROM 
	INVOICE_LINE IL
	JOIN TRACK T ON IL.TRACK_ID = T.TRACK_ID
	JOIN ALBUM A ON A.ALBUM_ID = T.ALBUM_ID
	JOIN ARTIST AR ON AR.ARTIST_ID = A.ARTIST_ID
	GROUP BY 1
	ORDER BY 3 DESC
	LIMIT 1
)

SELECT C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
BSA.ARTIST_NAME,
SUM(IL.UNIT_PRICE*IL.QUANTITY) AS AMOUNT_SPENT
FROM INVOICE I
JOIN CUSTOMER C ON C.CUSTOMER_ID = I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON IL.INVOICE_ID = I.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID = T.TRACK_ID
JOIN ALBUM A ON A.ALBUM_ID = T.ALBUM_ID
JOIN BEST_SELLING_ARTIST BSA ON BSA.ARTIST_ID = A.ARTIST_ID
GROUP BY 1,2,3,4
ORDER BY 5 DESC;

-- 3
WITH RECURSIVE
	CUSTOMER_WITH_COUNTRY AS(
		SELECT C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME,I.BILLING_COUNTRY,SUM(TOTAL) AS TOTAL_SPENDING
		FROM CUSTOMER C 
		JOIN INVOICE I ON C.CUSTOMER_ID = I.CUSTOMER_ID
		GROUP BY 1,2,3,4
		ORDER BY 1,5 DESC),
		
	COUNTRY_MAX_SPENDING AS(
		SELECT BILLING_COUNTRY,MAX(TOTAL_SPENDING) AS MAX_SPENDING
		FROM CUSTOMER_WITH_COUNTRY
		GROUP BY BILLING_COUNTRY)
		
SELECT CC.BILLING_COUNTRY,CC.TOTAL_SPENDING,CC.FIRST_NAME,CC.LAST_NAME,CC.CUSTOMER_ID
FROM CUSTOMER_WITH_COUNTRY CC
JOIN COUNTRY_MAX_SPENDING MS
ON CC.BILLING_COUNTRY =MS.BILLING_COUNTRY
WHERE CC.TOTAL_SPENDING =MS.MAX_SPENDING
ORDER BY 1
